### ISSUE TITLE
Global resource tests not running on Mill

### ISSUE THREAD

**Issue by RobinJDCox** [disneystreaming/weaver-test#113]
I'm having some trouble using global resource tests and I'm using Mill. This problem occurs with the latest version of Weaver (0.5.0).

If I define the following tests then neither of the two examples get run. I'm using ZIO, but have included both examples as I originally thought I'd done the Cats/ZIO interop wrong in the first example!

When running my tests, the test output prints the following which indicates that the `BasicGlobalInit` gets run but not the actual tests that are using it.

It feels like this might be a problem specifically when running on Mill, but I've not confirmed that.

Thanks

### Test Output
```
Shared resource create
done?
```

### Example
```scala
import cats.effect.{IO => CatsIO, Resource}
import weaver._
import weaver.ziocompat._
import zio._
import zio.interop.catz._

object BasicGlobalInit extends GlobalResourcesInit {

  def sharedResources(store: GlobalResources.Write[CatsIO]): Resource[CatsIO, Unit] = {
    println("Shared resource create")
    for {
      foo <- Resource.pure[CatsIO, String]("hello world!")
      _   <- store.putR(foo)
    } yield println("done?")
  }
}

class ZIOGlobalExample(globalResources: GlobalResources) extends ZIOSuite[Has[String]] {

  println("ZIO")

  override val sharedLayer: ZLayer[ZEnv, Throwable, Has[String]] =
    ZLayer.fromManaged {
      globalResources.in[CatsIO].getOrFailR[String]().toManaged
    }

  test("example") {
    ZIO.access[Has[String]](_.get).map { s =>
      expect(s == "hello world!")
    }
  }
}

class CatsGlobalExample(globalResources: GlobalResources) extends IOSuite {

  println("Cats")

  type Res = String
  override def sharedResource: Resource[CatsIO, Res] =
    globalResources.in[CatsIO].getOrFailR[String]()

  test("example") { s =>
    CatsIO { expect(s == "hello world!") }
  }
}

```

**Comment by keynmol** [comment]
@RobinJDCox did this end up being a Mill issue or still a weaver issue?

**Comment by Baccata** [comment]
@keynmol this is a mill issue. We can close this.

**Comment by RobinJDCox** [comment]
Yep, the Mill PR got merged which resolved my issue. Just waiting for the next release! 🙂 

Thanks guys
