### ISSUE TITLE
BSP integration w/ intellij doesn't work

### ISSUE THREAD

**Issue by dispalt** [disneystreaming/weaver-test#114]
I think it has to do with the code searching for a dependency that's prefixed with `sbt: ...` in the intellij module.

Also the plugin version doesn't match the published version. The xml file says 0.5.0, but after downloading and extracting the plugin and looking in the meta-inf folder, it's some older snapshot looking build.

**Comment by Baccata** [comment]
We're replacing the IDEA plugin by a [JUnit runner](https://github.com/disneystreaming/weaver-test/pull/244). Release to come today or tomorrow.

**Comment by dispalt** [comment]
Oh, great idea.
