### ISSUE TITLE
cannot update IDEA plugin to 0.5.0

### ISSUE THREAD

**Issue by mr-git** [disneystreaming/weaver-test#126]
IDEA offers update like `0.0.0+192-0bbb6421+20201007-2058 → v0.5.0`, but download fails

**Comment by keynmol** [comment]
What sort of error are you seeing? I just installed IntelliJ, then weaver plugin and then the upgrade to 0.5.0 worked

Granted, it's a fresh install of Idea :)

![image](https://user-images.githubusercontent.com/1052965/99875717-9e692f80-2be9-11eb-8aee-a5a536d57a9a.png)

**Comment by mr-git** [comment]
Sadly, I cannot find any error about weaver in IDEA log files.

After few attempts to update, IDEA doesn't see it sometimes, I have to "install" it again as saved int-test runner shows error: `Run Configuration Error: Broken configuration due to unavailable plugin or invalid configuration data.`

But, after I install 0.5.0, after restart it is gone, or back on `0.0.0+192-0bbb6421+20201007-2058`

Only other log entries about weaver plugin:
```
2020-11-21 19:14:11,177 [ 195779]   INFO - Settings.impl.PluginDownloader - Plugin disneystreaming.weaver-test: current version (max) 0.0.0+192-0bbb6421+20201007-2058 
2020-11-21 19:15:43,461 [ 288063]   INFO - lij.ide.plugins.DynamicPlugins - Plugin disneystreaming.weaver-test is not unload-safe because class loader cannot be unloaded 
```

**Comment by Baccata** [comment]
I've had a look at the CI build : https://cloud.drone.io/disneystreaming/weaver-test/335/1/4, it appears to be an issue of packaging, but the logs confirm that `0.0.0+192-0bbb6421+20201007-2058` and `0.5.0` are one and the same thing.

**Comment by Baccata** [comment]
We're replacing the IDEA plugin by a [JUnit runner](https://github.com/disneystreaming/weaver-test/pull/244). Release to come today or tomorrow.
