### ISSUE TITLE
https://disneystreaming.github.io/weaver-test/intellij.xml is offline

### ISSUE THREAD

**Issue by mr-git** [disneystreaming/weaver-test#149]
Cannot install or update plugin :(

**Comment by keynmol** [comment]
hi @mr-git, sorry bout that.

Can you try again? We had a very brief outage on the docs, but it's back up now :)

**Comment by Baccata** [comment]
@mr-git I'm on it, it should be fixed shortly

**Comment by Baccata** [comment]
@mr-git, it is back now, sorry for the inconvenience 😅
