### ISSUE TITLE
403 error updating weaver intellij plugin

### ISSUE THREAD

**Issue by amumurst** [disneystreaming/weaver-test#191]
Hi. 
I added attempted to add weaver plugin for intellij a couple of days ago, and yesterday I started getting 403 while updating.

<img width="744" alt="Screenshot 2021-02-02 at 10 24 36" src="https://user-images.githubusercontent.com/4258408/106579337-df15eb00-6540-11eb-924f-d3b53dcde0e8.png">

**Comment by Baccata** [comment]
Yeah we're unaware of what's causing this. I recommend uninstalling, and re-installing from disk downloading from [there](https://github.com/disneystreaming/weaver-test/releases/download/v0.5.1/weaver-intellij.zip).  

Full disclosure : we're planning on deprecating the intellij plugin in favour of a JUnit runner which should give us partial intellij integration "for free".
