### ISSUE TITLE
ExceptionInInitializerError when RuntimeException is thrown during a test, hangs sbt

### ISSUE THREAD

**Issue by qwbarch** [disneystreaming/weaver-test#222]
From discussion https://github.com/disneystreaming/weaver-test/discussions/221.

I've a piece of a code where it throws a RuntimeException, which causes it to hang sbt indefinitely.  
Here's an example to reproduce the issue:

```scala
import enumeratum.EnumEntry
import enumeratum.Enum
import weaver.SimpleIOSuite
import cats.effect.IO

sealed trait FatalSideEffectingEnum extends EnumEntry {

  import FatalSideEffectingEnum._

  val mightBoom = this match {
    case Safe => "safe"
    case Boom => throw new RuntimeException("boom")
  }
}

object FatalSideEffectingEnum extends Enum[FatalSideEffectingEnum] {

  val values = findValues

  case object Safe extends FatalSideEffectingEnum
  case object Boom extends FatalSideEffectingEnum
}

object FatalSqideEffectingTest extends SimpleIOSuite {

  test("FatalSideEffectingEnum should never throw a fatal exception") {
    IO(FatalSideEffectingEnum.values).attempt.map(either => expect(either.isRight))
  }
}
```

And here's my build.sbt file:
```scala
ThisBuild / scalaVersion := "2.13.4"

lazy val root = (project in file("."))
  .settings(
    testFrameworks += new TestFramework("weaver.framework.CatsEffect"),
    libraryDependencies ++= Seq(
      "com.beachape" %% "enumeratum" % "1.6.1",
      "com.disneystreaming" %% "weaver-cats" % "0.7.0-M6" % Test,
    )
  )
```

Stacktrace: https://pastebin.com/GPPwexzK

**Comment by Baccata** [comment]
Right so this is not a bug. Not on the weaver side anyway : throwing exception as part of the initialisation of a static object (your enumeration value) is bound to have problematic behaviour, in particular in the context of asynchronous computations. 

A colleague of mine had actually caught a similar problem and had raised an issue against [cats-effect](https://github.com/typelevel/cats-effect/issues/726). You'll be able to get an understanding of why this is not a bug by reading that issue.

**Comment by qwbarch** [comment]
Thanks for the clarification! The enum I'm using in my actual code-base throws a ``RuntimeException`` on invalid values (that are provided at compile-time) to prevent the server from starting at all if that were to happen, hence a test to make sure those values would always be correct.  

From the linked issue:

> I think I understand : the `new Thread` is not supervised by the `IO.async` function in any way (nor can it), and therefore there is no way for cats-effect to know that an exception happened in the thread, and it cannot react to it / propagate it. 

_Originally posted by @Baccata in https://github.com/typelevel/cats-effect/issues/726#issuecomment-565637371_

> Honestly you may not be able to do very much here. It depends on whether or not you can customize the thread pool underlying your `CompletableFuture`s. The correct way to lift async calls is probably the way you're doing it: use `IO.async(...).guarantee(IO.shift)` (to make sure you get back to the correct thread pool).

_Originally posted by @djspiewak in https://github.com/typelevel/cats-effect/issues/726#issuecomment-573142507_

Unfortunately it doesn't seem like there's a solution to this, but as you mentioned with erroring as part of the initialization of a static object, it seems more like a code-smell issue that I can resolve in another way.  Thanks again for the help!
