### ISSUE TITLE
Support overriding CheckConfig for individual forall's

### ISSUE THREAD

**Issue by nigredo-tori** [disneystreaming/weaver-test#265]
It doesn't always make sense to have the same configuration for each property. The only workaround is to split properties into separate suites based on their `CheckConfig`s - which is ugly.

**Comment by Baccata** [comment]
If you can come up with a solution that'd retain source compatibility and does not impact existing use, we're happy to look at PRs 😄

**Comment by Baccata** [comment]
I've had an idea on how to solve this and address and communicated it to a colleague of mine who'll have a go at implementing it.

**Comment by Baccata** [comment]
This is addressed and released. We haven't amended the docs yet, but you can now do `forall.withConfig(...){ ... } `
