### ISSUE TITLE
sbt reports success when global resource allocation fails

### ISSUE THREAD

**Issue by wedens** [disneystreaming/weaver-test#273]
When there is a global resource that fails to allocate, sbt reports tests as successful. No tests are executed, it just prints a stacktrace and finishes with success.

An example of such resource:
```scala
object TestResource extends GlobalResource {
  override def sharedResources(global: GlobalWrite): Resource[IO, Unit] =
    Resource.eval(IO.raiseError(new RuntimeException("TestResource")))
}
```

Consequently, this problem (when occurs) breaks CI as `sbt test` command returns zero code.

**Comment by Baccata** [comment]
Hi. Thanks for reporting, and sorry for the inconvenience. Due to the asynchronous nature of the flow at play, it's not totally trivial, but we'll do our best to address it asap !
