### ISSUE TITLE
How to run particular test file?

### ISSUE THREAD

**Issue by softshipper** [disneystreaming/weaver-test#31]
Hi all  
I would like to run only particular test file, for instance:
![Screenshot from 2020-07-01 10-12-31](https://user-images.githubusercontent.com/56756949/86220121-681c0c80-bb83-11ea-83f9-f248c836fa23.png)

Here, I would like to run only `InterestRouterSpec`.  

Thanks

**Comment by Baccata** [comment]
@softshipper, we're gonna need more information to help. In particular are you trying to : 

* run it from your IDE/editor (via right-click or whatever) ? In which case, which IDE are you using ? 
* run it from the terminal / the build tool's shell   ? In which case, which build tool are you using ?

**Comment by softshipper** [comment]
@Baccata 
I use Intellj but run tests via terminal with the statement `sbt test`. 
Does Intellj support `weaver-test`? I can not run like MUnit or ScalaTest, so debugging is not possible with Intellj.   

Thanks

**Comment by Baccata** [comment]
@softshipper I see. 

> Does Intellj support weaver-test? I can not run like MUnit or ScalaTest, so debugging is not possible with Intellj. 

we're looking into adding support for that, can't promise a specific timeframe though. 

> via terminal with the statement sbt test

Okay, so the sbt command you're looking for is [testOnly](https://www.scala-sbt.org/1.x/docs/Testing.html#testOnly). That'd look like `sbt "testOnly the.suite.qualified.Name"` (beware of the quotes). For instance, if your `UserRouteSpec`'s qualified name is `user.UserRouteSpec`, you could do `sbt "testOnly user.UserRouteSpec"` . You can also use wildcards, such as : 

```
> sbt "testOnly *User*" 
```

That being said, I highly recommend that you use sbt in REPL mode (ie just start a session using `sbt` in your terminal), as you'll be able to use `testOnly` with autocompletion

**Comment by softshipper** [comment]
Awesome @Baccata . Thanks a lot.
