### ISSUE TITLE
Examples from README.md seems not to work

### ISSUE THREAD

**Issue by bwiercinski** [disneystreaming/weaver-test#355]
I've pointed out errors

```scala
import weaver.IOSuite
import cats.effect._

object MySuite extends IOSuite {

  type Res = Int

  def sharedResource : Resource[IO, Int] = Resource
    .make(
      IO(println("Making resource"))
        .as(123)
    )(n => IO(println(s"Closing resource $n")))

  test("test, but resource not visible"){
    expect(123 == 123) // apply method is requiring IO[Expectations], not Expectations
  }

  test("test with resource"){ n =>
    expect(n == 123)
  }

  test("test with resource and a logger"){ (n, log) =>
    log.info("log was available") // log.info is an IO and needs to be executed using e.g. *>
    expect(n == 123)
  }
}
```

**Comment by Baccata** [comment]
Thanks for pointing this out ... we verify the snippets in the website using mdoc, but not the ones in the README, unfortunately.

**Comment by keynmol** [comment]
@Baccata given we can supply a custom file to mdoc command, we can run the check against readme as well.

Either that, or we commit to removing most of the examples from README and provide links to them instead. Your choice

**Comment by Baccata** [comment]
@keynmol verifying the readme would be cool actually, some people prefer looking at it than the website, so having a couple examples there is probably valuable. 

Created an issue : https://github.com/disneystreaming/weaver-test/issues/357
