### ISSUE TITLE
Publish weaver-monix for Scala 3

### ISSUE THREAD

**Issue by rgueldem** [disneystreaming/weaver-test#434]
Hi there! Would it be possible to publish weaver-monix for Scala 3? Monix itself is available for Scala 3 since 3.4.0. Are there any other blockers? Happy to help if needed.

```
sbt.librarymanagement.ResolveException: Error downloading com.disneystreaming:weaver-monix_3:0.6.7
```

**Comment by Baccata** [comment]
v0.6.8 is on its way :)
