### ISSUE TITLE
Add support for IntelliJ

### ISSUE THREAD

**Issue by richarddowsett** [disneystreaming/weaver-test#44]
It would be great to have the same feature set as other test frameworks and have the ability to run tests and suites directly from IntelliiJ. 

Given a test, IntelliJ should detect the presence of a weaver test and a suite and give the developer the ability to click to run a whole suite or a specific test

**Comment by Baccata** [comment]
Addressed https://disneystreaming.github.io/weaver-test/docs/intellij
