### ISSUE TITLE
The Great Schism 

### ISSUE THREAD

**Issue by keynmol** [disneystreaming/weaver-test#481]
We've toyed with the idea of dropping 2.12 and CE2 support at some point.
I propose we roll upgrade to Scala 3.1 in this as well.

Roughly, here is the way I see it:

- [ ] `series/0.6.x` branch is created, it's frozen at CE2 and for bugfixes only
- [ ] CE2 modules are removed from main branch
- [ ] Monix modules are removed from main branch (unless Monix makes it onto CE3)
- [ ] CE-shims are removed and replaced with concrete CE3 typeclasses and std classes
- [x] Scala 3 version is bumped to 3.1

   ~~If this happens late enough, we might have access to `-scala-release` flag, and can generate 3.0-compatible Tasty code.~~
   ~~That said, with the adoption figures the way they are, I say we encourage upgrade to 3.1.~~

   TEAM UPGRADE REPRESENT YO #542 

- [ ] (?) Semantics are adjusted to better take advantage of CE3 improvements
- [ ] 0.8.0 is released with only CE3 support
- [ ] Mima is enabled within the 0.8.x lineage (according to early-semver)

What do you think, @Baccata ?

**Comment by Baccata** [comment]
Yup, that's pretty much what I was thinking, so happy for this plan to be actioned!

**Comment by nlchar** [comment]
Will Scala 2 be still supported?

**Comment by keynmol** [comment]
Yes, I don't envision Scala 2 support going away at least in the couple of years.

**Comment by nlchar** [comment]
Thanks. Good to hear since almost all the community is still on Scala 2.

**Comment by keynmol** [comment]
All but one of those have been enacted, so I'm closing this with the impending release of a slimmed down 0.8.0
