### ISSUE TITLE
Configurable test start-up timeout

### ISSUE THREAD

**Issue by mcgizzle** [disneystreaming/weaver-test#489]
Hey, thanks for weaver, its a great lib :)

We have some integration tests where the startup can be _really_ slow.

It looks like weaver has a hard timeout of 120 seconds.

Is there a way to increase this?

```
java.util.concurrent.TimeoutException: Future timed out after [120 seconds]
```

**Comment by mcgizzle** [comment]
It looks the timeout is set here

https://github.com/disneystreaming/weaver-test/blob/5eda2f229a0084ad98be47c88b3872bb62f8cbea/modules/framework/src-jvm/RunnerCompat.scala#L124

**Comment by Baccata** [comment]
Hey @mcgizzle, sorry for not replying earlier, I've been uber busy. As a short term solution, I'm happy to merge a patch that'd increase this to an arbitrarily large number (if you could just indulge me by creating the PR). I'd insta-release right after the patch is merged to unblock you. 

We could take it one step further and make it configurable via an env-var (to avoid impacting much of the code) :  

Something like : 

```scala
val maybeTimeout = sys.env.get("WEAVER_RESOURCE_TIMEOUT_SECONDS").flatMap { timeoutString => 
   try { Some(timeoutString.toInt) } catch { case _ : Throwable => None } // can't use `toIntOption` because 2.12  
}.map(_.seconds) 
scala.concurrent.Await.result(gate.future, maybeTimeout.getOrElse(120.seconds) 
```

**Comment by keynmol** [comment]
Perhaps system properties?
As that's what, say, CE uses to configure the runtime and tracing

**Comment by Baccata** [comment]
whichever would be fine

**Comment by mcgizzle** [comment]
Thanks for getting back to me, happy to make the patch myself.

I'll have a look the system properties approach, sounds reasonable.

**Comment by mcgizzle** [comment]
https://github.com/disneystreaming/weaver-test/pull/491
