### ISSUE TITLE
Use both Discipline and MutableIOSuite

### ISSUE THREAD

**Issue by bwiercinski** [disneystreaming/weaver-test#528]
is it possible to use **shared resource** from MutableIOSuite inside **checkAll** from Discipline addon?

**Comment by Baccata** [comment]
Mmm yeah, that's a fair point I guess. In this case I'd be happy to review a PR adding this feature 😄

**Comment by bwiercinski** [comment]
grrr 😄 

how to achive this? currently `Discipline` trait have a self-type of `FunSuiteAux` (`trait Discipline { self: FunSuiteAux => ... }`)

obviously i have to use something that relays on `MutableFSuite` (which is a abstract class). should i create trait `Discipline2` which have `trait DisciplineIT[F[_]] { self: MutableFSuite[F] => ... }`?

if i would like to edit current Discipline trait it would be binary incompatible although the users would only need to change:
```diff
+object FooLawTests extends FunSuite with Discipline {
-object FooLawTests extends SimpleMutableIOSuite with Discipline {

  checkAll("foo", FooTests(implementation).foo)

+  pureTest("if someone added any unit test) { ... }
-  test("if someone added any unit test) { ... }
}
```

**Comment by Baccata** [comment]
Yeah let's try to make a new trait instead (could call it `DisciplineEffect` or whatever), in order to avoid breaking current usecases. Not that I think there are many of the, but still.

**Comment by bwiercinski** [comment]
I'm in a crossroad right now. At first I wanted to use `trait DisciplineEffect[F[_]] { self: MutableFSuite[F] => ... }`. Its not so easy:
In standard suite all tests are collected using `MutableFSuite.registerTest`. If after filtering number of tests is 0 then there is no need to allocate resource.

In case of law testing I want to define following function `checkAll(name: String, input: Res => F[Laws#RuleSet])` (one `Laws#RuleSet` contains many tests). So I want to firstly open a resource and then register tests, because without the resource I dont know how many tests there will be.

* I can modify `MutableFSuite` to contain instead of 
```diff
+var testSeq = Seq.empty[(TestName, Res => F[TestOutcome])]
-var testSeq = Seq.empty[Res => F[List[(TestName, TestOutcome)]]]
```
I'm losing benefit of not opening a resource in some cases. **Is that something to concern or hardly ever used feature?**

* I can modify `MutableFSuite` to contain instead of 
```diff
+var testSeq = Seq.empty[(TestName, Res => F[TestOutcome])]
-var testSeq = Seq.empty[Either[(TestName, Res => F[TestOutcome]),Res => F[List[(TestName, TestOutcome)]]]]
```
**Complicated**, but i can achieve the feature

* Create Suite only for Discipline testing: Will all features work well (eg. Global resource, filtering etc) Who knows :)

**Comment by Baccata** [comment]
the `def plan: List[TestName]` is required in order for users to benefit from the out-of-the-box JUnit integration in Intellij. 

I think this is sufficient to justify that it should be its own Suite, as opposed to extending the existing `MutableFSuite`. The most abstract thing you can extend is [this](https://github.com/disneystreaming/weaver-test/blob/c99cced2af84d7f5598bb1773d6e4c0c49f1d991/modules/core/src/weaver/suites.scala#L14-L17), and I'd probably start there, as you'll be able to go 100% Pure FP. 

* Global resources should work 
* You'll have to handle filtering yourself

**Comment by bwiercinski** [comment]
without runnable suite I'm unable to run it via intellij or sbt
