### ISSUE TITLE
Integration with allure

### ISSUE THREAD

**Issue by nlchar** [disneystreaming/weaver-test#560]
How can we achieve integration with allure? Does it exist now? Where should it be placed if we implement it? One option is https://github.com/allure-framework/allure-java

**Comment by Baccata** [comment]
> How can we achieve integration with allure

I presume you could have a mix-in that'd override the [spec method](https://github.com/disneystreaming/weaver-test/blob/master/modules/core/src/weaver/suites.scala#L16) to add an effect of reporting to the allure backend, or something.  To be honest I'm not sure why allure doesn't provide a build-plugin adapter, considering the build tool probably receives all the information allure needs. 

> Does it exist now

I'm not aware of such an integration. 

> Where should it be placed if we implement it? 

Not in this repo. If the allure-framework people want to host such an integration, it's their prerogative. I presume it could be in a repo you control.

**Comment by Baccata** [comment]
Closing because this falls out of the scope of Weaver.
