### ISSUE TITLE
Support for multiple shared resources in a test suite

### ISSUE THREAD

**Issue by pshirshov** [disneystreaming/weaver-test#6]
Hi,

It would be nice to support wiring multiple shared resources per test suite. We have supported such scenario in [`distage-testkit`](https://izumi.7mind.io/distage/distage-testkit.html#testkit) and would be happy to share our experience if you wish.

**Comment by Baccata** [comment]
Hi, thanks for opening the issue.

We aren't really looking into providing this. Resource being a compositional construct, the decision was made to leave the user compose resources into a single value however they deem relevant. We're really wanting to keep the framework lean in that regard.

**Comment by pshirshov** [comment]
In case resources have some cross-dependencies it may be not so nice to wire them manually.
Regarding being lean - core distage logic has just ~300 LoC

**Comment by Baccata** [comment]
> In case resources have some cross-dependencies it may be not so nice to wire them manually.

Manual wiring is actually something we're pretty happy with, despite some induced boilerplate.

That being said, the particular trait you're referring to in this issue about is (I assume) `IOSuite`, which is not the most generic one. There's a number of other traits that can be extended, the most generic one being [https://github.com/disneystreaming/weaver-test/blob/master/modules/core/src/weaver/suites.scala#L16-L19] 

Maybe a `distage` specific (or inspired) module could be created to extend one of the more generic traits allow for the usecase you're thinking about ?

**Comment by Baccata** [comment]
[Addressed](https://disneystreaming.github.io/weaver-test/docs/global_resources)
