### ISSUE TITLE
`ignore` doesn't work in pure specs / pure tests

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/weaver-test#608]
```scala
//> using lib "com.disneystreaming::weaver-cats:0.8.0"
import weaver._

object Demo extends FunSuite {
  test("foo".ignore) {
    failure("wat")
  }
}
```

<img width="519" alt="image" src="https://user-images.githubusercontent.com/894884/202597597-307da0e3-e486-4847-a71d-3c2ef11a2f5e.png">

**Comment by kubukoz** [comment]
Also, I don't think the check for `CI=true` works:

```scala
//> using lib "com.disneystreaming::weaver-cats:0.8.0"
import weaver._
import cats.effect.IO

object Demo extends SimpleIOSuite {
  println(System.getenv("CI"))

  test("foo".ignore) {
    IO.pure(failure("wat"))
  }

  pureTest("foo-pure".ignore)(failure("wat2"))
}
```

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/894884/202833236-36ecc035-71fc-499b-b5b5-0f1890f1127b.png">

**Comment by Baccata** [comment]
> Also, I don't think the check for CI=true works

Maybe because we've not actually released it ?

**Comment by kubukoz** [comment]
lol. Guess I should've started with that.

**Comment by kubukoz** [comment]
wanna release? :P

**Comment by Baccata** [comment]
Yeah let's fix the pure tests indeed.

**Comment by kubukoz** [comment]
I'm on it.
