### ISSUE TITLE
How to execute some cleanup action after each test on shared resources?

### ISSUE THREAD

**Issue by szymonprz** [disneystreaming/weaver-test#629]
Hi I have a simple question for you guys :) Is there an option to perform some cleanup after each/before each test execution using shared resource?

**Comment by Baccata** [comment]
Nothing out of the box, but it's quite simple to achieve in userland, it looks roughly like : 

```scala 
def beforeAndAfterEach(shared: Res) : Resource[IO, Something] = ??? 
def myTest(name: TestName)(run: Something => IO[Expectations]) : Unit = test(name){ shared => 
  beforeAndAfterEach(shared).use(run)
}
```

and then call `myTest` to create tests.

**Comment by szymonprz** [comment]
@Baccata thank you very much, this is what I needed  ❤️
