### ISSUE TITLE
Busy spin in `SbtTask` results in high CPU usage

### ISSUE THREAD

**Issue by dimitarg** [disneystreaming/weaver-test#671]
Consider 

```scala
package repro
import cats.effect.IO
import scala.concurrent.duration._
import weaver.SimpleMutableIOSuite

object Repro extends SimpleMutableIOSuite {
  test("asd") {
    IO.sleep(120.seconds).as(success)
  }
}
```

This will result in 100% CPU usage (i.e. 1 core) for the duration of the run.
The reason appears to be `while (!finished && !isDone.get()) {` in `SbtTask.execute`, which is in effect a busy spin (until `isDone` is done).

Of course, feel free to close at your discretion if this is deemed not an issue.

**Comment by Baccata** [comment]
To be honest it's kinda expected. However it could be good to experiment with blocking queues instead of concurrent linked queues. 

Unfortunately I'm lacking the capacity to explore this short term.
