### ISSUE TITLE
Setup Github actions

### ISSUE THREAD

**Issue by keynmol** [disneystreaming/weaver-test#71]
At the moment I maintain the docker image that builds things on drone, because we need lots of stuff.

We can probably get away with some of the built-in github actions instead.

**Comment by bfdes** [comment]
Do we want to both test and publish on Actions?

**Comment by keynmol** [comment]
If we were to switch, it would have to be in full.

I also feel like we can just copy the work flows from mdoc almost verbatim... https://www.github.com/scalameta/mdoc/tree/master/.github%2Fworkflows

**Comment by bfdes** [comment]
I think I can take a look this weekend.

**Comment by Baccata** [comment]
Addressed in https://github.com/disneystreaming/weaver-test/pull/230
