### ISSUE TITLE
Publish docs using commits from main; not just tags

### ISSUE THREAD

**Issue by mcanlas** [disneystreaming/weaver-test#738]
We had talked in person last year about surfacing documentation updates at a cadence sooner than tagged releases

- I think changes would need to be made to the CI GHA file, allowing the step to trigger on `main`
- But also the underlying ammonite/`sc` side effect inside of it would need to be rethought. Seems like it is versioning its artifacts? With `main` updates, how would that work?

**Comment by Baccata** [comment]
The stewardship of weaver is being moved to Typelevel. This repo will not see any further development or release, unless specifically to fix a critical bug. 

The documentation updates on the TL repo will follow whatever the TL setup does. 

Closing the issue for the reason stated above.
