### ISSUE TITLE
Make intellij plugin work resource-sharing suites 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/weaver-test#80]
Suites that have a constructor that takes a `GlobalResources` instance do not seem to be detected by the Intellij plugin. 

See [gitter](https://gitter.im/disneystreaming/weaver-test?at=5f61903af51808513b47965c)

**Comment by keynmol** [comment]
Could this be due to us forcing objects?

https://github.com/disneystreaming/weaver-test/blob/0.5.0-series/modules/intellij/src/main/scala/weaver/intellij/testsupport/WeaverTestFramework.scala#L40

**Comment by Baccata** [comment]
Partly, the runner needs to add a little bit of [logic](https://github.com/disneystreaming/weaver-test/blob/0.5.0-series/modules/intellij-runner/src/weaver/intellij/runner/WeaverTestRunner.scala#L39) to handle classes. 

Just to be clear : addressing this will still make suites subject to the [same limitation](https://disneystreaming.github.io/weaver-test/docs/global_resources#regarding-testonly-build-tool-commands) currently experienced by `testOnly` usage, namely folks will have to manually add some recovery mechanism

**Comment by Baccata** [comment]
We're replacing the IDEA plugin by a [JUnit runner](https://github.com/disneystreaming/weaver-test/pull/244). Release to come today or tomorrow.
