### ISSUE TITLE
Investigate integration with monix-bio

### ISSUE THREAD

**Issue by keynmol** [disneystreaming/weaver-test#81]
[monix-bio](https://github.com/monix/monix-bio) is in 1.x version, so we can probably assume that it's stable.

It's worth looking into integrating with it to provide full coverage of IO monads in existence. Worth checking with maintainers if the API is considered stable.

**Comment by Baccata** [comment]
Already pinged @bfdes as he's done the monix Task integration. Most of it will be copy/paste.

**Comment by Baccata** [comment]
Addressed in #83
